language: python
sudo: required

services:
  - docker

install:
  - pip install requests simplejson 
  - make docker
  - make run
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - 

script:
  - python test/tests.py

after_script:
  - make log
  - make stop


deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: key-value-tarantool
  on:
    repo: Alex-Kuz/tarantool-key-value-store
    branch:
      - feature-deploy
      - develop
  skip_cleanup: true
